<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="TYSS-Sanjay" failures="1" tests="3" name="Test1" time="84.124" errors="0" timestamp="22 May 2024 12:15:47 GMT">
  <testcase classname="com.comcast.crm.organizationtest.CreateOrganizationTest" name="createOrg" time="29.326"/>
  <testcase classname="com.comcast.crm.organizationtest.CreateOrganizationTest" name="createOrgWithIndustry" time="12.999"/>
  <testcase classname="com.comcast.crm.organizationtest.CreateOrganizationTest" name="createOrganizationWithphonenumbertest" time="13.34">
    <failure type="java.lang.AssertionError" message="expected [Whatsapp_4446] but found [9876766400]">
      <![CDATA[java.lang.AssertionError: expected [Whatsapp_4446] but found [9876766400]
at com.comcast.crm.organizationtest.CreateOrganizationTest.createOrganizationWithphonenumbertest(CreateOrganizationTest.java:83)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- createOrganizationWithphonenumbertest -->
</testsuite> <!-- Test1 -->
